version: '3.1'
services:
  db:
    image: postgres:14.6
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    # Create a volume to persist data
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: